# **19CSE305:MACHINE LEARNING LAB 1- NUMPY**

SIKHA O K

References: Github reppositories, Tutorial Point

# **Python for Machine Learning**

**Introduction to NUMPY- "Numerical Python"**

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.The most powerful feature of NumPy is n-dimensional array. This library also contains basic linear algebra functions, Fourier transforms, advanced random number capabilities and tools for integration with other low level languages like Fortran, C and C++

**Arrays**

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:


In [ ]:
#Import Numpy and check the version. The version string is stored under version attribute.
import numpy as np
print(np.__version__)

1.19.5


The array object in NumPy is called ndarray. 
We can create a NumPy ndarray object by using the array() function.

In [ ]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print("the shape:",arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
the shape: (4,)


**0-Dimension arrays**

In [ ]:
arr0=np.array(43)
print(arr0)
print("The shape: ",arr0.shape)

43
The shape:  ()


**1-D array:** An array with 0-dimensional array as elements 

In [ ]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print('The shape: ',arr.shape)
print("Number of elements of the array:",arr1.size)

[1 2 3 4 5 6]
The shape:  (6,)
Number of elements of the array: 6


**2D array:** An array that has 1-D arrays as its elements. hese are often used to represent matrix or 2nd order tensors.

In [ ]:
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr2)
print("The shape: ",arr2.shape)
print("Total number of elements",arr2.size)

[[1 2]
 [3 4]
 [5 6]]
The shape:  (3, 2)
Total number of elements 6


**3D array:** array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.

In [ ]:
arr3=np.array([[[1,2], [3,4]],[[5,6],[7,8]],[[8,9],[9,90]]])
print(arr3)
print("The shape: ",arr3.shape)
print("Total number of elements",arr3.size)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 8  9]
  [ 9 90]]]
The shape:  (3, 2, 2)
Total number of elements 12


**Check Number of Dimensions**:  NumPy Arrays provides the ***ndim ***attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("The shape of array a:",a.ndim)
print("The shape of array b:",b.ndim)
print("The shape of array c:",c.ndim)
print("The shape of array d:",d.ndim)


The shape of array a: 0
The shape of array b: 1
The shape of array c: 2
The shape of array d: 3


**Higher Dimensional Array:**s An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('Dimension of the array is: ',arr.ndim)
#In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector,
# the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

[[[[[1 2 3 4 5]]]]]
Dimension of the array is:  5


In [ ]:
# dtype parameter 
a = np.array([1, 2, 3], dtype = complex) 
print(a)


[1.+0.j 2.+0.j 3.+0.j]


**Reshape an array**

In [ ]:
a=np.array([[1,2,3],[5,6,7]])
print("Shape of the original array: ", a.shape)
print("The original array:\n",a)
#resize the array as (3,2)
a.shape=(3,2)
print("Reshaped array:\n",a)
print("Shape of the reshaped array: ", a.shape)


Shape of the original array:  (2, 3)
The original array:
 [[1 2 3]
 [5 6 7]]
Reshaped array:
 [[1 2]
 [3 5]
 [6 7]]
Shape of the reshaped array:  (3, 2)


In [ ]:
#NumPy also provides a reshape function to resize an array.
a=np.array([[1,2,3],[5,6,7]])
print("Shape of the original array: ", a.shape)
print("The original array:\n",a)
#resize the array as (3,2)
a=a.reshape(3,2)
print("Reshaped array:\n",a)
print("Shape of the reshaped array: ", a.shape)

Shape of the original array:  (2, 3)
The original array:
 [[1 2 3]
 [5 6 7]]
Reshaped array:
 [[1 2]
 [3 5]
 [6 7]]
Shape of the reshaped array:  (3, 2)


**Array Indexing**

In [ ]:
arr = np.array([1, 2, 3, 4])

print('first element: ', arr[0])
print('second element: ', arr[1])

first element:  1
second element:  2


In [ ]:
#Get third and fourth elements from the following array and add them.
arr = np.array([1, 2, 3, 4])


In [ ]:
#2d array
arr=np.array([[1,2],[3,4]])
print('Element (0,0): ',arr[0,0])
print('Element (1,1): ',arr[1,1])

Element (0,0):  1
Element (1,1):  4


In [ ]:
#3D array:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#Print the second element of the second array of the first array

print(arr[0,1,1])
# First number represents first dimension,which has three arrays: [1 2] [3 4] , [5 6] [7 8] and [9 10] [11 12]. We select 0 hence [1 2] [3 4]
# Second number represents second dimension which has two  arrays: [ 1 2] [ 3 4]. We chose 1 hence [3 4]
#Thirf number  represents one dimension which has two  values: 3, 4 . We chose 1 hence 4


**Array Slicing**

Slicing arrays Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
#Slice the values from 1 to 5
print('Values 1 to 5:', arr[1:5])
#Display the first 8 numbers
print('First 8 elemns: ',arr[0:7])
#Display the last 3 numbers
print('Last 3 numbers',arr[-3:])
#print alternative elements
print('Alternative:',arr[0:9:2])

Values 1 to 5: [2 3 4 5]
First 8 elemns:  [1 2 3 4 5 6 7]
Last 3 numbers [ 8  9 10]
Alternative: [1 3 5 7 9]


In [ ]:
# array to begin with 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:' )
print (a) 
print ('\n' ) 

# this returns array of items in the second column 
print ('The items in the second column are:'  )
print (a[:,1] )
print ('\n'  )

# Now we will slice all items from the second row 
print ('The items in the second row are:' )
print (a[1,:] )
print ('\n'  )

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:' )
print (a[:,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [ ]:
#2d slicing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
#From both elements, return index 2
print(arr[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]


**Check the datatype**

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array(['all','is','well'])
print('array1: ',arr1.dtype)
print('array2: ',arr2.dtype)

array1:  int64
array2:  <U4


**Creating Arrays With a Defined Data Type**

In [ ]:
arr=np.array([1,2,3,4],dtype='S')
print(arr.dtype)

|S1


**Converting Data Type of Existing Arrays**

In [ ]:
arr=np.array([1.1,2.2,3.4,5.6])
print('array elements: ',arr)
print('Initial array data type: ',arr.dtype)
arr1=arr.astype('i')
print('Converted array elements: ',arr1)
print('Converted array datatype: ',arr1.dtype)

array elements:  [1.1 2.2 3.4 5.6]
Initial array data type:  float64
Converted array elements:  [1 2 3 5]
Converted array datatype:  int32


**Random Array:** Generate Random Number NumPy offers the random module to work with random numbers.

In [ ]:
#Generate a random integer from 0 to 100:
x=np.random.randint(100)
print('Random numbers from 1-100: ', x)

Random numbers from 1-100:  9


In [ ]:
#Generate Random Float The random module's rand() method returns a random float between 0 and 1.
x=np.random.rand()
print(x)

0.054963220296496695


**Array math**

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print("Matrix Addition: \n")
print (x + y)
print("\n")
print ("\nUsing np.add: \n",np.add(x, y))
print("\n")
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print (x - y)
print (np.subtract(x, y))


print("Matrix Multiplication: \n")

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print( x * y)
print("\n")
print ("Using np.multiply:\n",np.multiply(x, y))
print("\n")

print("Matrix Devison: \n")
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print("\n")
print ("Using np.divide:\n",np.divide(x, y))
print("\n")
print("Elementwise squart:\n")
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

Matrix Addition: 

[[ 6.  8.]
 [10. 12.]]



Using np.add: 
 [[ 6.  8.]
 [10. 12.]]


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
Matrix Multiplication: 

[[ 5. 12.]
 [21. 32.]]


Using np.multiply:
 [[ 5. 12.]
 [21. 32.]]


Matrix Devison: 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Using np.divide:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


Elementwise squart:

[[1.         1.41421356]
 [1.73205081 2.        ]]


Explore the following Numpy functions from[ here](https://numpy.org/doc/stable/)

* array()
* type()
* ndim
* [start:end:step]
* dtype
* copy()
* view()
* reshape()
* concatenate()
* array_split()
* where()
* searchsorted()    
* sort()
* randint()
* rand()
* shuffle()
* permutation()
* binomial()
* multinomial()
* exponential()
* add()
* prod()
* cumprod()
* diff()
* unique()
* lcm()
* linspace()
* gcd()
* sin()
* sinh()
